#!/bin/bash

if [ $(id -u) -eq 0 ]
then
	clear
else
	if echo $(id) |grep sudo > /dev/null
	then
	clear
	echo "Voce não é root"
	echo "Seu usuario esta no grupo sudo"
	echo -e "Para virar root execute \033[1;31msudo su\033[0m"
	exit
	else
	clear
	echo -e "Vc nao esta como usuario root, nem com seus direitos (sudo)\nPara virar root execute \033[1;31msu\033[0m e digite sua senha root"
	exit
	fi
fi

if [ -d /etc/Packvpsdir ]
then
echo ""
else
mkdir /etc/Packvpsdir
fi

if [ -d /etc/Packvpsdir/senha ]
then
echo ""
else
mkdir /etc/Packvpsdir/senha
fi

if [ -d /etc/Packvpsdir/limite ]
then
echo ""
else
mkdir /etc/Packvpsdir/limite
fi

clear
echo -e "\033[1;37m Packvpset © Rogerfran \033[0m"
echo -e "\033[1;37mEscolha uma das opçoẽs:    \033[1;37mPara Sair Ctrl + C\033[1;33m
[1] limitessh \033[1;30m(limite de conexoes simultaneas)\033[1;33m
[2] criaruser \033[1;30m(Criar usuarios)\033[1;33m
[3] modificar \033[1;30m(Opções para mudanças no usuario)\033[1;33m
[4] removerusuario \033[1;30m(Deletar, Desconectar, Opções)\033[1;33m
[5] firewallblok \033[1;30m(Regras iptables block torrent, icmp [RISCOS])\033[1;33m
[6] firewallresertar \033[1;30m(Retira todas as regras iptables [RISCOS])\033[1;33m
[7] install-addhost \033[1;30m(Faz a preparaçao para add-host)\033[1;33m
[8] addhost \033[1;30m(Adicionar hosts aceitos pelo squid )\033[1;33m
[9] monitor \033[1;30m(IMPORTANTE monitorar conexões por usuarios)\033[0m\033[1;33m
[10] beckupuser \033[1;30m(Backup dos usuarios para reinstalação futura)\033[1;33m
[11] restaurar \033[1;30m(Restaurar usuarios feito backup)\033[1;33m
[12] detalhesuser \033[1;30m(Mostra informações sobre os usuarios !!)\033[1;33m
[13] banner \033[1;30m(Banner mensagem no ssh)\033[1;33m
[14] speedteste \033[1;30m(Teste de conexão [velocidade de banda])\033[1;33m
[15] detalhessystem \033[1;30m(Detalhes sobre o Sistema [Created BadGuy])\033[1;33m
[16] detalhes \033[1;30m(Detalhes sobre o VpsPack)\033[1;33m
[17] desistalar \033[1;30m(Remover o VpsPack)\033[0m"
read -p ": " opcao

case $opcao in
 1)
  read -p "Usuario: " user
  read -p "Limite de Conexoes: " limit
  limitessh $user $limit;;
 2)
  criaruser;;
 3)
  modificar;;
 4)
  removerusuario;;
 5)
  firewallblok;;
 6)
  firewallresertar;;
 7)
  install-addhost;;
 8)
  addhost;;
 9)
  monitor;;
 10)
  beckupuser;; 
 11)
  read -p "Em qual diretorio esta o arquivo de Backup: " arq 
  restaurar $arq;;
 12)
  detalhesuser;;
 13)
  banner;;
 14)
  speedteste;;
 15)
  detalhessystem;;
 16)
  detalhes;;
 17)
  desistalar;;
 *)
  id > /dev/null 2> /dev/null
esac
